name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Pushes to companion-xmltotsforms repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COMPANION_XMLTOTSFOMRS_API_TOKEN }}
        with:
          source-files: 'test/'
          destination-username: 'springcard'
          destination-repository: 'companion-xmltotsforms'
          destination-directory: 'xml'
          destination-branch: 'dev'
          commit-email: 'codechef730@gmail.com'
